ci:
  collect:
    url:
      - /
      - /cookbook
      - /musings
      - /me
    staticDistDir: ./public
  assert:
    # Categories and Assertions can be found here:
    #   https://github.com/GoogleChrome/lighthouse/blob/v5.5.0/lighthouse-core/config/default-config.js#L374
    assertions:
      categories:performance:
        - error
        - minScore: .9
      categories:accessibility:
        - error
        - minScore: .9
      categories:best-practices:
        - error
        - minScore: .9
      categories:seo:
        - error
        - minScore: .85
      categories:pwa:
        - error
        - minScore: .9
