#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Raise an error if more than 50 warnings are generated
  max-warnings: 10
# Rule Configuration
rules:
  attribute-quotes: 2
  bem-depth: 2
  border-zero: 2
  brace-style:
    - 2
    - style: stroustrup
      allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedbem
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-args: 2
  empty-line-between-blocks:
    - 2
    - include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - mq

  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  function-name-format:
    - 2
    - convention: camelcase
  mixin-name-format:
    - 2
    - convention: camelCase
  variable-name-format:
    - 2
    - convention: hyphenatedbem

  hex-length: 2
  hex-notation: 2

  indentation: 2
  nesting-depth: 2

  leading-zero: 0
  max-file-line-count: 2
  max-line-length: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 2
  no-combiners: 0
  no-css-comments: 2
  no-debug: 1
  no-warn: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  property-sort-order: 2
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-before-bang: 2
  space-after-bang: 2
  space-before-colon: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
  # x
  #
  # placeholder-in-extend: 2
  # no-warn: 1
  # no-debug: 1
  # no-ids: 2
  # no-important: 2
  # hex-notation:
  #   - 2
  #   - style: lowercase
  # indentation:
  #   - 2
  #   - size: 2
  # property-sort-order:
  #   - 2
  #   - order:
  #       - display
  #       - margin
  #     ignore-custom-properties: true
  # variable-for-property:
  #   - 2
  #   - properties:
  #       - margin
  #       - content
