# Shared Folders
folders:
  source: src # Asset, JavaScript, Service Worker, and Sass source folder
  pages: views # HTML source, relative to project root
  templates: templates # HTML templates, relative to project root
  includes: _components # HTML includes, relative to template directory
  layouts: _layouts # HTML layouts, relative to template directory
  output: public # Output folder for all files

# JavaScript Input/Output Config
#   output: input
#     output - Output file (no extension)
#     input - Input file (with extension) from folders.source
javascript:
  esm:
    js/main: js/main.js
  iife:

# Service Worker Config
serviceWorker:
  src: sw.js
  dest: sw.js
  precache: # Glob patterns to precache when Service Worker is installed
    - css/**/*.css
    - js/**/*.js
    - _components/**/*.txt

# Sass Config
sass:
  src: sass/**/*.scss
  dest: css
  lint: true
  config:
    outputStyle: compressed

# Static Asset Folders
assets:
  images:
    src: images/**/*
    dest: images
  videos:
    src: videos/**/*
    dest: videos
  fonts:
    src: fonts/**/*
    dest: fonts
  manifest:
    src: manifest.json
    dest: ''

# HTML Optimization
#   src is relative to the _output_ folder, not the pages or source folder.
optimize:
  src:
    - '**/*.html'
    - '**/*.txt'
  critical:
    inline: true
    minify: true
  htmlmin:
    collapseWhitespace: true
    sortAttributes: true
    sortClassNames: true
