name: Build and Deploy

concurrency: production

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - sanity_deploy

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Test and Build
        run: npm t
        env:
          SANITY_PROJECT: ${{ secrets.SANITY_PROJECT }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
