name: Node CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Switch Node Version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npm ci
      - name: Build and Test
        run: |
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: Upload built state
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: public
      - name: Upload compiled dependencies
        uses: actions/upload-artifact@v1
        with:
          name: dependencies
          path: node_modules

  # lighthouse:
  #   needs: build-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Download compiled site
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: site
  #     - name: Lighthouse Audit
  #       uses: treosh/lighthouse-ci-action@v2
  #       with:
  #         urls: |
  #           /
  #           /cookbook
  #           /musings
  #           /me
  #         configPath: .lighthouserc.json
  #         temporaryPublicStorage: true

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Switch Node Version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download compiled site
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: dependencies
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
