name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Test and Build
        run: npm t
        env:
          SANITY_PROJECT: ${{ secrets.SANITY_PROJECT }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
